---
title: "R Notebook"
output:
  pdf_document: default
  html_notebook: default
---

```{r}
data1<-read.table("/Users/phamkhoa/Documents/university/3/stats_model_1/w2/canoladiesel.txt", sep="\t", dec=".", header=TRUE)
attach(data1)
```

```{r}
# Problem 1

#a
model.inv1.ex1<-glm(Yield~Time, family = gaussian(link = "inverse"), data = data1)
summary(model.inv1.ex1)

newdata <-data.frame(Time = 40)
predict(model.inv1.ex1, newdata = newdata, type = "response")

```
```{r}
#b
model.inv1gamma.ex1<-glm(Yield~Time, family = Gamma(link = "inverse"), data = data1)
model.identity1gamma.ex1<-glm(Yield~Time, family = Gamma(link = "identity"), data = data1)
model.log1gamma.ex1<-glm(Yield~Time, family = Gamma(link = "log"), data = data1)


AIC(model.identity1gamma.ex1)
AIC(model.inv1gamma.ex1)
AIC(model.log1gamma.ex1)

# choose (i) log link model

```
```{r}
#c
model.log123gamma.ex1<-glm(Yield ~ Time + Temp + Methanol, family = Gamma(link = "log"), data=data1)
summary(model.log123gamma.ex1)

newdata <-data.frame(Time = 40, Temp = 260, Methanol = 1.75)
pred<-predict(model.log123gamma.ex1, type="response", level=0.95, newdata=newdata, se.fit = TRUE)

eta<-predict(model.log123gamma.ex1, type="link", newdata=newdata, se.fit = TRUE) 
link.lowerbound<-eta$fit-qnorm(0.975)*eta$se.fit
link.upperbound<-eta$fit+qnorm(0.975)*eta$se.fit

upper<-exp(link.upperbound) ### !!!!
lower<-exp(link.lowerbound) ### !!!!
upper
lower
# 95% CI = (38.51991, 68.33616)
```
```{r}
#d
gammaH0 <- glm(Yield ~ Time + Temp, family = Gamma(link = "log"), data=data1)
test<-anova(gammaH0, model.log123gamma.ex1, test = "F")
test$`Pr(>F)`
```

```{r}
#e
model.e.N <- glm(Yield ~ Time + Temp + Methanol, family = gaussian(link = "log"), data=data1)
model.e.G <- glm(Yield ~ Time + Temp + Methanol, family = Gamma(link = "log"), data=data1)
model.e.IG <- glm(Yield ~ Time + Temp + Methanol, family = inverse.gaussian(link = "log"), data=data1)

AIC(model.e.N)
AIC(model.e.G)
AIC(model.e.IG)

## MSE

mean(residuals(model.e.N, type="pearson")^2)
mean(residuals(model.e.G, type="pearson")^2)
mean(residuals(model.e.IG, type="pearson")^2)

shapiro.test(residuals(model.e.N, type="pearson"))
shapiro.test(residuals(model.e.G, type="pearson"))
shapiro.test(residuals(model.e.IG, type="pearson"))

#plot(fitted(model.e.N, type="response"), residuals(model.e.N, type="pearson")^2)
#plot(fitted(model.e.G, type="response"), residuals(model.e.G, type="pearson")^2)
#plot(fitted(model.e.IG, type="response"), residuals(model.e.IG, type="pearson")^2)

plot(model.e.N$y, residuals(model.e.N, type="pearson"))
plot(model.e.G$y, residuals(model.e.G, type="pearson"))
plot(model.e.IG$y, residuals(model.e.IG, type="pearson"))

# Based on my analysis, I choose the inverse gaussian distrbution 
#as it yield the highest p for normality test for Pearson's residual. 
#IG distribtution also have the lowest MSE
```
```{r}
#Problem 2
data2<-read.table("/Users/phamkhoa/Documents/university/3/stats_model_1/w2/ratstime.txt", sep="\t", dec=".", header=TRUE)
attach(data2)
```

```{r}
#a
N.p2<-glm(time~factor(poison) + factor(treat), family = gaussian("identity"), data = data2)
G.p2<-glm(time~factor(poison) + factor(treat), family = Gamma("identity"), data = data2)
IG.p2<-glm(time~factor(poison) + factor(treat), family = inverse.gaussian("identity"), data = data2)

AIC(N.p2)
AIC(G.p2)
AIC(IG.p2)

## MSE

mean(residuals(N.p2, type="response")^2)
mean(residuals(G.p2, type="response")^2)
mean(residuals(IG.p2, type="response")^2)

shapiro.test(residuals(N.p2, type="pearson"))
shapiro.test(residuals(G.p2, type="pearson"))
shapiro.test(residuals(IG.p2, type="pearson"))

#I choose the model N.p2 (normal distribution identity link) 
#as it have the smallest MSE and highest p for shapiro test

```
```{r}
#b
p2b.identity<-glm(time~factor(poison) + factor(treat), family = Gamma("identity"), data = data2)
p2b.log<-glm(time~factor(poison) + factor(treat), family = Gamma("log"), data = data2)
p2b.inverse<-glm(time~factor(poison) + factor(treat), family = Gamma("inverse"), data = data2)

mean(residuals(p2b.identity, type="response")^2)
mean(residuals(p2b.log, type="response")^2)
mean(residuals(p2b.inverse, type="response")^2)

# From the MSE value, choose inverse link with gramma distribution as it has the smallest MSE
```
```{r}
#c
ig.H0<-glm(time~factor(poison) + factor(treat), family = inverse.gaussian("log"), data = data2)
ig.H1<-glm(time~factor(poison)*factor(treat), family = inverse.gaussian("log"), data = data2)
anova(ig.H0, ig.H1, test = "F")
#Pr(>F) = 0.1176 
```

```{r}
#d
newdata<-data.frame(poison = "II", treat = "B")
pred<-predict(p2b.log, newdata=newdata, type="response")
pred

xf<-cbind(c(1,1,0,1,0,0))

Var.Yf<-summary(p2b.log)$dispersion
D.f<-pred
Var.ef<-Var.Yf+(D.f^2)*t(xf)%*%vcov(p2b.log)%*%xf

lower.yf<-pred-qnorm(0.9)*sqrt(Var.ef)
upper.yf<-pred+qnorm(0.9)*sqrt(Var.ef)

lower.yf
#[1,] lower 0.4027708
upper.yf
#[1,] upper 1.058068

```


```{r}
#e
newdata<-data.frame(poison = c("I","II"), treat = c("D","B"))
pred<-predict(p2b.log, newdata=newdata, type="response")
pred

x1<-cbind(c(1,0,0,0,0,1))
x2<-cbind(c(1,1,0,1,0,0))
Xf<-t(cbind(x1,x2))
k<-cbind(c(-1,1))

phi<-summary(p2b.log)$dispersion
Var.Y1f<-phi*(pred[1]^2)
Var.Y2f<-phi*(pred[2]^2)

D.f<-diag(pred)  

Var.ef<-Var.Y1f+Var.Y2f+t(k)%*%D.f%*%Xf%*%vcov(p2b.log)%*%t(Xf)%*%D.f%*%k

lower.diff<-(pred[2]-pred[1])-qnorm(0.9)*sqrt(Var.ef)
upper.diff<-(pred[2]-pred[1])+qnorm(0.9)*sqrt(Var.ef)
lower.diff
upper.diff
#(-0.3167109, 0.3717572)
```

